/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
	#include "stdint.h"
	#include "string.h"
	#include "stdio.h"
	#include "stdlib.h"
	#include "stdbool.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0  (GUI_ID_USER + 0x00)
#define ID_BUTTON_0  (GUI_ID_USER + 0x01)
#define ID_BUTTON_1  (GUI_ID_USER + 0x02)
#define ID_BUTTON_2  (GUI_ID_USER + 0x03)
#define ID_BUTTON_3  (GUI_ID_USER + 0x04)
#define ID_BUTTON_4  (GUI_ID_USER + 0x05)
#define ID_BUTTON_5  (GUI_ID_USER + 0x06)
#define ID_BUTTON_6  (GUI_ID_USER + 0x07)
#define ID_BUTTON_7  (GUI_ID_USER + 0x08)
#define ID_BUTTON_8  (GUI_ID_USER + 0x09)
#define ID_BUTTON_9  (GUI_ID_USER + 0x0A)
#define ID_BUTTON_10  (GUI_ID_USER + 0x0B)
#define ID_BUTTON_11  (GUI_ID_USER + 0x0C)
#define ID_BUTTON_12  (GUI_ID_USER + 0x0D)
#define ID_BUTTON_13  (GUI_ID_USER + 0x0E)
#define ID_BUTTON_14  (GUI_ID_USER + 0x0F)
#define ID_BUTTON_15  (GUI_ID_USER + 0x10)
#define ID_BUTTON_16  (GUI_ID_USER + 0x11)
#define ID_BUTTON_17  (GUI_ID_USER + 0x12)
#define ID_TEXT_0  (GUI_ID_USER + 0x13)
#define ID_EDIT_0  (GUI_ID_USER + 0x14)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
	double first=0, second=0;
	bool flag_1=false, flag_2=false, divisionError=false;
	double digit_1=1, digit_2=1;
	double result=0;
	int which=0;
	char myOperator='+';
	char display[100] = "";
	char error[100] = "error"; 
	char test;
	int idx=0;
	int i=0;
//	static TS_StateTypeDef  TS_State;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 8, 11, 480, 270, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "3", ID_BUTTON_0, 15, 90, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "6", ID_BUTTON_1, 15, 135, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "9", ID_BUTTON_2, 15, 180, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "0", ID_BUTTON_3, 15, 45, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "1", ID_BUTTON_4, 105, 45, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "4", ID_BUTTON_5, 105, 90, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "7", ID_BUTTON_6, 105, 135, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, ".", ID_BUTTON_7, 105, 180, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "2", ID_BUTTON_8, 195, 45, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "5", ID_BUTTON_9, 195, 90, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "8", ID_BUTTON_10, 195, 135, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "00", ID_BUTTON_11, 195, 180, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "+", ID_BUTTON_12, 285, 45, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "-", ID_BUTTON_13, 285, 90, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "*", ID_BUTTON_14, 285, 135, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "/", ID_BUTTON_15, 285, 180, 90, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Clear", ID_BUTTON_16, 375, 45, 90, 90, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "=", ID_BUTTON_17, 375, 135, 90, 90, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 199, 225, 80, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 99, 9, 280, 30, 0, 0x14, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
void displayOnLcd(char *,WM_HWIN,WM_MESSAGE *);

void analyze_string()
{
		static int x=0;
		for(x=0 ; x<strlen(display);x++)
		{
				if(42<=display[x] && display[x]<=47 && display[x]!=46)
					which++;
				switch (which){
					case 0:
						if(display[x]!=46){
							first *= 10;
							first += display[x]-48;
							if(flag_1 == true)
								digit_1 *= 10;
						}
						else
							flag_1 = true;
					break;
					case 1:
						myOperator = display[x];
						first /= digit_1;
						which++;
					break;
					case 2:
						if(display[x]!=46){
							second *= 10;
							second += display[x]-48;
							if(flag_2 == true)
								digit_2 *= 10;
						}
						else
							flag_2 = true;
					break;
				}
		}
		second/=digit_2;
		digit_1 = 1;
		digit_2 = 1;
		flag_1 = false;
		flag_2 = false;
		which = 0;
}

void addValueToDisplay(char newNum)
{
	display[idx] = newNum;
	idx++;
}



// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	//uint8_t displays[50] = "";
	
	//WM_HWIN hItem;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "NTUST");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF8000));
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "");
    EDIT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by '3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				addValueToDisplay('3');
				displayOnLcd(display,hItem,pMsg);
				        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by '6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        addValueToDisplay('6');
				displayOnLcd(display,hItem,pMsg);
				        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '9'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        addValueToDisplay('9');
				displayOnLcd(display,hItem,pMsg);
				        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by '0'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        addValueToDisplay('0');
				displayOnLcd(display,hItem,pMsg);
				        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by '1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        addValueToDisplay('1');
				displayOnLcd(display,hItem,pMsg);
				        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by '4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					addValueToDisplay('4');
					displayOnLcd(display,hItem,pMsg);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by '7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        addValueToDisplay('7');
				displayOnLcd(display,hItem,pMsg);
				        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by '.'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        addValueToDisplay('.');
				displayOnLcd(display,hItem,pMsg);
				        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by '2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        addValueToDisplay('2');
				displayOnLcd(display,hItem,pMsg);
				        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by '5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        addValueToDisplay('5');
				displayOnLcd(display,hItem,pMsg);
				        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by '8'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        addValueToDisplay('8');
				displayOnLcd(display,hItem,pMsg);
				        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by '00'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        addValueToDisplay('0');
			  addValueToDisplay('0');
				displayOnLcd(display,hItem,pMsg);
				        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_12: // Notifications sent by '+'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
       /* if(idx == 0)
					addValueToDisplay('0');*/
				addValueToDisplay('+');
				displayOnLcd(display,hItem,pMsg);
				        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_13: // Notifications sent by '-'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        /*if(idx == 0)
					addValueToDisplay('0');*/
				addValueToDisplay('-');
				displayOnLcd(display,hItem,pMsg);
				        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_14: // Notifications sent by '*'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        /*if(idx == 0)
					addValueToDisplay('0');*/
				addValueToDisplay('*');
				displayOnLcd(display,hItem,pMsg);
				        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_15: // Notifications sent by '/'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				
				/*if(idx == 0)
					addValueToDisplay('0');*/
        addValueToDisplay('/');
				displayOnLcd(display,hItem,pMsg);
				        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_16: // Notifications sent by 'Clear'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        memset( display, 0, 100	);
				display[0] = '0';
				displayOnLcd(display,hItem,pMsg);
				memset( display, 0, 100 );
				idx = 0;
				first = 0;
				second = 0;
				        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_17: // Notifications sent by '='
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				analyze_string();
				switch (myOperator){
					case '+':
						result = first + second;
					break;
					case '-':
						result = first - second;
					break;
					case '*':
						result = first * second;
					break;
					case '/':
						if(second == 0)
							divisionError = true;
						result = first / second;
					break;
				}
				if(idx < 2)
				{	
					memset( display, 0, 100 );
					display[0] = '0';
					displayOnLcd(display,hItem,pMsg);
				}
				else
				{
					if((long long int)result == result)	//result is integer
					{
						sprintf(display,"%10lld",(long long int)result);
					}
					else	//result is float
					{						
						sprintf(display,"%.8lf" , result);
						char temp[50];
						int x=0;
						bool flag = false;
						for(x=strlen(display)-1 ; x>=0 ;x--)
						{
							if(display[x] == '0')
								display[x] = '\0';
							else
								break;
						}
					}
					display[10] = '\0';
					if(divisionError == true)
					{
						int x=0;
						for(x=0;x<strlen(error);x++)
							display[x] = error[x];
						display[x] = '\0';
						divisionError = false;
					}
					displayOnLcd(display,hItem,pMsg);
				}
				memset( display, 0, 100 );
				idx = 0;
				first = 0;
				second = 0;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
void displayOnLcd(char *displayLcd , WM_HWIN hItem , WM_MESSAGE* pMsg)
{
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		EDIT_SetText(hItem, display);
		EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
}
// USER END

/*************************** End of file ****************************/
